### ISSUE TITLE
Readonly doesn't work on name field

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.UIBuilder.Issues#111]
**Describe the bug**
I have something something like the following which set login name in name property, but calling `.MakeReadOnly()` on this, doesn't make the name field readonly.

```
.AddUIBuilder(cfg =>
{
    cfg.AddSectionAfter("media", "Repositories", sectionConfig => sectionConfig
        .Tree(treeConfig => treeConfig
            .AddCollection<MemberDto>(x => x.NodeId, "Member", "Member", "A member entity", "icon-umb-users", "icon-umb-users", collectionConfig => collectionConfig
                .SetNameProperty(p => p.LoginName).MakeReadOnly()
                .ListView(listViewConfig => listViewConfig
                    .AddField(p => p.LoginName).SetHeading("Login")
                    .AddField(p => p.Email)
                )
                .DisableCreate()
                .DisableDelete()
                .DisableUpdate()
            )
        )
    );
}) 
```

![image](https://github.com/user-attachments/assets/55f4200c-cdae-4f81-ab16-8a1b0a0f39b0)

**Environment (please complete the following information):**
 - Server OS: Windows 10
 - Browser Chrome
 - Umbraco Version 13.4.1
 - Product Version 13.1.5

---
_This item has been added to our backlog AB#45968_

**Comment by creativesuspects** [comment]
@bjarnef I believe you can use `SetNameFormat()` instead of `SetNameProperty()` to hide the name field at the top, or at least this is/was the case in Konstrukt. You just see the name of the collection at the top:

![image](https://github.com/user-attachments/assets/80f0973a-65a5-4517-8bb5-879ed36895e4)

In my project the Field name had to be 'Name' otherwise sorting on that column didn't work for some reason:

`.SetNameFormat(x => x.Name)`

**Comment by bjarnef** [comment]
`.SetNameFormat(x => x.LoginName)` kinda works, but it didn't set `LoginName` as header name, but the parent tree node as name.

so header name is the same when accessing all entities.

**Comment by creativesuspects** [comment]
Yeah, it just shows the name of the collection in the header. But is that really such a big deal? The `LoginName` is already being displayed in your General section, right?

**Comment by bjarnef** [comment]
Yes.. we can always show the properties in the view itself. But I think it makes more sense to show name (login) property as header name than the parent node name :)

**Comment by acoumb** [comment]
Hi @bjarnef ,

I can see in your code snippet that you're missing an `Editor` fluent configuration. Without it you would not be able to get an edit view where you would toggle the readonly on a specific property.

What is the specific use case you are trying to put in place?

Thanks,
Adrian

**Comment by bjarnef** [comment]
Hi @acoumb

Can you elaborate where the `Editor` is missing or show an updated code sample?

The use-case is that we have custom function adding logs entries in a custom table with has a column referencing member guid.

As the `Member` dto class in Umbraco is internal I made a copy of this.

It then list members and for each member filtered logs.

However we just want to make the list of members readonly - it is just to get and overview and browse logs for a specific member.

Perhaps this part could also be combined within a `.MakeReadOnly()` method?

```
.DisableCreate()
.DisableDelete()
.DisableUpdate()
```

**Comment by acoumb** [comment]
@bjarnef 
So disable the name column from being clickable?
![image](https://github.com/user-attachments/assets/1897fd37-7779-47d1-b22d-edb128999055)

**Comment by bjarnef** [comment]
@acoumb no. The name input in header.

![image](https://github.com/user-attachments/assets/264eac80-e9d6-496e-86c4-099532a1f0a1)

**Comment by bjarnef** [comment]
@acoumb I think the name input in header has a readonly property or similar, but it seems UI Builder doesn't set this property.

**Comment by acoumb** [comment]
Indeed @bjarnef, there is a switch between input view and label view. An update for this I expect to go out next week.

**Comment by acoumb** [comment]
@bjarnef this has been addressed with recent patch releases on UIBuilder.

**Comment by umbracocommunity** [comment]
This issue has been mentioned on **Umbraco community forum**. There might be relevant details there:

https://forum.umbraco.com/t/readonly-content-name-field/5090/1
