### ISSUE TITLE
Searchable property in listview only match first word

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.UIBuilder.Issues#116]
**Describe the bug**
When added the following to a listview collection:

```
.AddSearchableProperty(x => x.Message)
```

a search field is shown. However entering a term only search match start on message text. So if message contains term, which is not first word, then no results are found.

**Steps To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Server OS: Windows 10
 - Browser Chrome Version 129.0.6668.101
 - Umbraco Version 13.4.1
 - Product Version 13.1.5

---
_This item has been added to our backlog AB#45966_

**Comment by acoumb** [comment]
Hi @bjarnef ,
An update for this has been released with the latest minor release of UIBuilder. The updated [documentation](https://docs.umbraco.com/umbraco-ui-builder/searching/searchable-properties) will soon reflect the update.

Thanks,
Adrian

**Comment by bjarnef** [comment]
@acoumb it doesn't seem this has been fixed?

Using UI Builder v13.2.0

Searching first word in property find match.

![Image](https://github.com/user-attachments/assets/0003d33b-94f1-461e-a98d-57c6b0a6384f)

But not in rest of message.

![Image](https://github.com/user-attachments/assets/2d388a8b-0fd7-4c5b-bb9d-f2c8c7d7d2f4)

**Comment by acoumb** [comment]
Hi @bjarnef ,

It has been fixed, you would need to use the method overload that takes the `Contains` pattern.

```
AddSearchableProperty(x => x.Message, SearchExpressionPattern.Contains)
```

**Comment by bjarnef** [comment]
@acoumb thanks :)

`SearchExpressionPattern` has two options:

- `StartsWith`
- `Contains`

Would it be possible to have a `Is` and `Exact` to align with DeliveryAPI filters? E.g. to search match on `Guid` or `int` id.
Most of the time `StartsWith` is fine though, but consider a field value contains 1, 11 or 111, etc. and one want to match value `1` (not 11 and 111).

**Comment by acoumb** [comment]
Thanks @bjarnef , I will look into your suggestions.
