### ISSUE TITLE
Run server side validation on action settings dialog

### ISSUE THREAD

**Issue by mattbrailsford** [umbraco/Umbraco.UIBuilder.Issues#34]
Currently when edditing the settings of an action, we can add required validation no problem, but regex validation doesn't work.

On further investigation this looks to be because Umbraco performs regex validation server side and so we need to find a way to perform the server side validation.

I think we may need to add an endpoint explicitly for validating a model and have that run the validation tests and return the results for Konstrukt to check before closing the dialog and continuing.

---
_This item has been added to our backlog AB#34773_

**Comment by acoumb** [comment]
Feature implemented with following versions of `Umbraco.UIBuilder`:
- [10.0.2](https://www.nuget.org/packages/Umbraco.UIBuilder/10.0.2)
- [12.0.2](https://www.nuget.org/packages/Umbraco.UIBuilder/12.0.2)
