### ISSUE TITLE
Boolean property not rendered correctly with .AddFilterableProperty(p => p.BooleanField

### ISSUE THREAD

**Issue by matt-tolliday-iss** [umbraco/Umbraco.UIBuilder.Issues#63]
**Describe the bug**
When using FilterableProperty with a boolean type, the rendered UI component is a free text field, which is not suitable.

**Steps To Reproduce**
1. Configure a bool property with .AddFilterableProperty(p => p.BooleanField)
2. Field is rendered with a text box

**Expected behavior**
Should be rendered with a radio/picker suitable for boolean value that binds to a bool property.

**Screenshots**

**Comment by matt-tolliday-iss** [comment]
@mattbrailsford would there be any update on this at all please?

**Comment by mattbrailsford** [comment]
So I've made an update that should be on the unstable build shortly https://nuget.outfield.digital/unstable/v3/index.json

This should be able to handle booleans, however it does so in a specific way. Which is if the boolean flag is true, it will affect the results, but if it's false, it won't apply a negative filter. Give it a try and let me know if this works for you.

**Comment by matt-tolliday-iss** [comment]
Fantastic @mattbrailsford - exactly what was needed!

**Comment by mattbrailsford** [comment]
This was pushed out in [1.6.6](https://www.nuget.org/packages/Konstrukt/1.6.6) a few days ago
