### ISSUE TITLE
Set datatype by guid

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.UIBuilder.Issues#67]
It seems currently the `SetDataType()` has two overload methods:

```
SetDataType(string name)
SetDataType(int id)
```

but I think if would be great to have `SetDataType(Guid id)` as well if having multiple environments, where the id may not be identical and the downside with datatype name is that I guess it will break if the datatype instance is renamed :)

![image](https://github.com/umbraco/Umbraco.UIBuilder.Issues/assets/2919859/051a4dcc-6737-43b1-9275-da954d9b7a23)

**Comment by bjarnef** [comment]
Btw. I opening this as a bug since the "Features and Ideas" opens:
https://github.com/outfielddigital/konstrukt/discussions

The "Support Question" and "Documentation Issue" may also need to be updated.

**Comment by mattbrailsford** [comment]
So I quickly added a fix and I've pushed a nightly to the Umbraco nightly feed if you'd like to try that https://docs.umbraco.com/umbraco-cms/fundamentals/setup/install/installing-nightly-builds 12.0.1--preview.5

**Comment by mattbrailsford** [comment]
Implemented in 10.0.1 and 12.0.1
