### ISSUE TITLE
Dependency issue when installing UIBuilder alongside uSync in a v12 Umbraco website

### ISSUE THREAD

**Issue by JamesDodwell** [umbraco/Umbraco.UIBuilder.Issues#72]
I have an Umbraco 12 site. I've installed Umbraco.UIBuilder (12.0.0) but now it won't run.  This appears to be a dependency issue because uSync (12.1.0) and Umbraco.UIBuilder.Web.StaticAssets (12.0.0) have dependcy on different versions of Microsoft.AspNetCore.Components.Web.

**Steps To Reproduce**
1. Run a v12 Umbraco site
2. Install uSync (12.1.0)
3. Install Umbraco.UIBuilder.Web.StaticAssets (12.0.0)
4. dotnet run
5. See the following error...

![Screenshot 2023-11-01 170836](https://github.com/umbraco/Umbraco.UIBuilder.Issues/assets/10656559/a586db4b-c76e-47c0-9096-14d674a607cd)

---
_This item has been added to our backlog AB#34767_

**Comment by JamesDodwell** [comment]
Right, I have just installed the following version from the Nightlies:

`dotnet add package Umbraco.UIBuilder --version 12.0.2--preview.1`

 and it's now working!

**Comment by mattbrailsford** [comment]
That’s awesome James. I’ll reopen the issue for now, mostly as a reminder for me to process this issue properly later. Glad the fix worked for you.
