### ISSUE TITLE
Make whereClause nullable in custom repo overrides

### ISSUE THREAD

**Issue by jemayn** [umbraco/Umbraco.UIBuilder.Issues#75]
**Describe the bug**
If I create my own repo for the data in UI Builder then it will generate the methods to override for me via the IDE.

However, some of them has an expression parameter for a whereClause:

```csharp
protected override IEnumerable<Movie> GetAllImpl(Expression<Func<Movie, bool>> whereClause, Expression<Func<Movie, object>> orderBy, SortDirection orderByDirection)
{
    throw new NotImplementedException();
}

protected override PagedResult<Movie> GetPagedImpl(int pageNumber, int pageSize, Expression<Func<Movie, bool>> whereClause, Expression<Func<Movie, object>> orderBy,
    SortDirection orderByDirection)
{
    throw new NotImplementedException();
}

protected override long GetCountImpl(Expression<Func<Movie, bool>> whereClause)
{
    throw new NotImplementedException();
}
```

And if no filters or anything is added then the whereClause is null, which means we need to have a nullcheck for it, but our IDE will constantly tell us that the null check is not needed:

![image](https://github.com/umbraco/Umbraco.UIBuilder.Issues/assets/79840720/158d556d-6c33-4331-97a0-16d0b47fe142)

![image](https://github.com/umbraco/Umbraco.UIBuilder.Issues/assets/79840720/011489ba-cce8-4f71-bbfb-67f4bc24b44d)

Would be nice if the method set the Expression as nullable.

**Environment (please complete the following information):**
 - Server OS: windows
 - Browser any
 - Umbraco Version 12.3.1
 - Product Version 12.0.1

**Comment by acoumb** [comment]
Hi @jemayn ,

We have addressed this with the latest [major](https://www.nuget.org/packages/Umbraco.UIBuilder/13.0.0) release of Umbraco.UIBuilder.

Regards,
Adrian
