### ISSUE TITLE
Not populating $scope.model.dataTypeKey, problems using Contentment Data Picker

### ISSUE THREAD

**Issue by brannmark** [umbraco/Umbraco.UIBuilder.Issues#76]
**Describe the bug**
When using Contentment Data Picker we noticed a problem. UI builder is not populating $scope.model.dataTypeKey which Contentment use for the data picker. 
More info on the bug here: [https://github.com/leekelleher/umbraco-contentment/issues/368#issuecomment-1814249813](https://github.com/leekelleher/umbraco-contentment/issues/368#issuecomment-1814249813)

**Steps To Reproduce**
1. Create a datatype using Contentment Data Picker
2. Add as datatype for a field in UI Builder
3. Try to use the data picker
4. See error in throwing a 404 because dataTypeKey is empty GUID.

**Screenshots**

**Environment (please complete the following information):**
 - Umbraco Version 12.3.1
 - UI Builder Version 12.0.1
 - Contentment 4.5.1

---
_This item has been added to our backlog AB#35174_

**Comment by acoumb** [comment]
Hi @brannmark ,

I have released version [12.0.2](https://www.nuget.org/packages/Umbraco.UIBuilder/12.0.2) of `Umbraco.UIBuilder` with a fix to this issue.

Thank you,
Adrian
