### ISSUE TITLE
Make the type in GetImpl nullable in custom repos

### ISSUE THREAD

**Issue by jemayn** [umbraco/Umbraco.UIBuilder.Issues#77]
**Describe the bug**
I am implementing a custom repo for a UI Builder collection like this:

```
public class MovieUiBuilderRepository : Repository<Movie, int>


protected override Movie GetImpl(int id)
{
        throw new NotImplementedException();
}
```

However, based on just an ID we can't guarantee that the T type (Movie in my case) exists. It would be nice to have an option to say the T type with the id doesn't exist.

Easiest way would be if it was nullable and we could just return null.

---
_This item has been added to our backlog AB#35173_

**Comment by acoumb** [comment]
Hi @jemayn ,

We have addressed this with the latest [major](https://www.nuget.org/packages/Umbraco.UIBuilder/13.0.0) release of Umbraco.UIBuilder.

Regards,
Adrian
