### ISSUE TITLE
Missing `DataTypeKey` in PropertyDisplayModel

### ISSUE THREAD

**Issue by andrewmckaskill** [umbraco/Umbraco.UIBuilder.Issues#80]
**Describe the bug**
I am trying to use Contentment data picker inside UI-Builder. It's failing because it is missing the `DataTypeKey` property inside its editor model.

I have validated through debugging that adding this property resolves the issue and allows contentment data-picker to work inside UI-Builder.

Samples:
- Data returned by `GetEntityScaffold` api - see "dataTypeKey" is all zeros.
![image](https://github.com/umbraco/Umbraco.UIBuilder.Issues/assets/32095907/9173edb0-0af5-4411-857e-04c4df82ae0e)

- The property is not being set inside `Umbraco.UIBuilder.Web.Models.Mappers.ToContentPropertyDisplayModel`

- When all zeros, it causes Contentment to issue a request to: `/umbraco/backoffice/Contentment/DataPickerApi/GetItems?id=-1&dataTypeKey=00000000-0000-0000-0000-000000000000` which fails with 
"Unable to locate data source for data type: '00000000-0000-0000-0000-000000000000" as it uses the dataTypeKey to lookup to relevant configuration information.

---
_This item has been added to our backlog AB#35772_

**Comment by andrewmckaskill** [comment]
Note: this property is present when using the dataPicker inside a content item, just not a ui-builder item.

Angular model of editor when used inside content item:
![image](https://github.com/umbraco/Umbraco.UIBuilder.Issues/assets/32095907/2e4544e5-83f0-4df6-bed9-4defbc4d777e)


Angular model of editor when used inside ui-builder item:
![image](https://github.com/umbraco/Umbraco.UIBuilder.Issues/assets/32095907/6fe62fe9-b841-4b1d-a178-04a790fbf075)

**Comment by acoumb** [comment]
Hi @andrewmckaskill ,

This issue has been fixed with the latest patch releases - [10.0.2](https://www.nuget.org/packages/Umbraco.UIBuilder/10.0.2)/[12.0.2](https://www.nuget.org/packages/Umbraco.UIBuilder/12.0.2).

Thank you,
Adrian
