### ISSUE TITLE
RTE not rendering anymore

### ISSUE THREAD

**Issue by brannmark** [umbraco/Umbraco.UIBuilder.Issues#81]
**Describe the bug**
Using RTE fails after upgrade to latest version. Only displays loading dots when trying to render.
![image](https://github.com/umbraco/Umbraco.UIBuilder.Issues/assets/1013748/cfb4c44e-6f07-4688-b311-ecdc370a2f8b)

**Steps To Reproduce**
1. Add a property with a RTE datatype
2. Try to edit the entity
3. See error

**Expected behavior**
Render the RTE editor.

**Screenshots**
![image](https://github.com/umbraco/Umbraco.UIBuilder.Issues/assets/1013748/5878f1e9-a033-45f5-962a-d115fec2be5e)

**Environment (please complete the following information):**
 - Browser Chrome
 - Umbraco Version 13.0.1
 - Product Version 13.0.0

**Additional context**
Throws a javascript error "Could not find umbVariantContent" in console when trying to edit an entity with a RTE datatype.
![image](https://github.com/umbraco/Umbraco.UIBuilder.Issues/assets/1013748/5857fc9c-8580-4877-9fd3-88fc9985abc1)

---
_This item has been added to our backlog AB#36102_

**Comment by brannmark** [comment]
Marking it state/sprint-candidate meaning what? Has it been resolved, when will it be released, mayor issue this as RTE must be one of the most used editors on this product?

**Comment by AndyButland** [comment]
"state/sprint-candidate" is a tag we added to indicate that we plan to look into in in an upcoming sprint... in this case being this one.

**Comment by nathanwoulfe** [comment]
Likely related to https://github.com/umbraco/Umbraco-CMS/issues/15474

**Comment by acoumb** [comment]
Hi @brannmark ,

The issue has been fixed by the CMS team with the latest RC release [13.1.0-rc](https://www.nuget.org/packages/Umbraco.Cms/13.1.0-rc).

Regards,
Adrian
