### ISSUE TITLE
Fields in Sidbar are not included when creating item

### ISSUE THREAD

**Issue by patlit** [umbraco/Umbraco.UIBuilder.Issues#82]
Fields in Sidebar is not included in form-data when creating a new item.
If field is moved to "standard" fieldset it is included.

![image](https://github.com/umbraco/Umbraco.UIBuilder.Issues/assets/54680084/106ca6e6-0d5b-46d9-ab3f-e3c8c2b93d84)

![image](https://github.com/umbraco/Umbraco.UIBuilder.Issues/assets/54680084/e877660d-4839-4f31-b2d6-ae9338eb6136)

![image](https://github.com/umbraco/Umbraco.UIBuilder.Issues/assets/54680084/a8d7c1c7-5c80-49f9-a7b2-f398b005b9eb)

 - Umbraco Version 12.2.0
 - Umbraco UI Builder 12.0.2

---
_This item has been added to our backlog AB#36362_

**Comment by acoumb** [comment]
Hi @patlit ,

Thank you for catching this. The issue has been fixed with the latest patch releases: 
- [12.0.3](https://www.nuget.org/packages/Umbraco.UIBuilder/12.0.3)
- [13.0.2](https://www.nuget.org/packages/Umbraco.UIBuilder/13.0.2)

Regards,
Adrian
