### ISSUE TITLE
Contentment Data picker not rendering in UI builder actions

### ISSUE THREAD

**Issue by brannmark** [umbraco/Umbraco.UIBuilder.Issues#83]
**Describe the bug**
Datatype with a data picker in a custom UI builder action doesn't work. It does not render as supposed to.

Throw following error:
![image](https://github.com/umbraco/Umbraco.UIBuilder.Issues/assets/1013748/6ff176bf-81a7-44f2-a1a2-84a9db5d5a79)

Using this code for custom action:
```
using Umbraco.UIBuilder.Configuration;
using Umbraco.UIBuilder.Configuration.Actions;
using Umbraco.UIBuilder.Configuration.Builders;
using Umbraco.UIBuilder.Services;
using IHostingEnvironment = Umbraco.Cms.Core.Hosting.IHostingEnvironment;

namespace MyProj.Actions.BulkActions
{
	public class TestAction : Umbraco.UIBuilder.Configuration.Actions.Action<TestActionSetting, ActionResult>
    {
        public override string Icon => "icon-edit";
        public override string Alias => "test";
        public override string Name => "Test";
        public override bool ConfirmAction => false;
        private readonly Lazy<UIBuilderConfig> _config;
        private readonly Lazy<EntityService> _entityService;
        private readonly Lazy<IHostingEnvironment> _hostingEnv;

        public TestAction(Lazy<UIBuilderConfig> config, Lazy<EntityService> entityService, Lazy<IHostingEnvironment> hostingEnv)
        {
            _config = config;
            _entityService = entityService;
            _hostingEnv = hostingEnv;
        }

        public override void Configure(SettingsConfigBuilder<TestActionSetting> settingsConfig)
        {
            settingsConfig.AddFieldset("Content", fieldsetConfig =>
            {
                fieldsetConfig.AddField(m => m.TestProperty).SetDataType("Test");
			});
        }

        public override ActionResult Execute(string collectionAlias, object[] entityIds, TestActionSetting settings)
        {
            return new ActionResult(true, new ActionNotification("Test action executed"));
        }

        public override bool IsVisible(ActionVisibilityContext ctx)
        {
            if (ctx.ActionType == ActionType.Row || ctx.ActionType == ActionType.Bulk)
            {
                return true;
            }
           
            return false;
        }
    }

    public class TestActionSetting
    {
        public string TestProperty { get; set; } = string.Empty;
    }
}
```

Datatype:
![image](https://github.com/umbraco/Umbraco.UIBuilder.Issues/assets/1013748/a7447a37-e674-4dfa-af6f-8a268ca185e0)

Collection:
![image](https://github.com/umbraco/Umbraco.UIBuilder.Issues/assets/1013748/be6d7942-30fd-4233-9b3e-4625c1a5b771)

Rendering:
![image](https://github.com/umbraco/Umbraco.UIBuilder.Issues/assets/1013748/9a1dc999-c579-4fcd-b4c6-b10f040f32c5)

**Steps To Reproduce**
1, Create a datatype using Data Picker
2. Create a custom action for UI Builder
3. Create a customer Settings Model
4. Add datatype with data picker to the settings model in configure
5. Add action to an UI Builder collection
6. Click on action
7. See property but no editor rendered.

**Expected behavior**
Expected editor to be rendered.

**Environment (please complete the following information):**
 - Server OS: Windows
 - Browser Chrome
 - Umbraco Version 13.0.3
 - Product Version 13.0.0

**Additional context**
Also submitted here: https://github.com/leekelleher/umbraco-contentment/issues/374

---
_This item has been added to our backlog AB#36292_

**Comment by acoumb** [comment]
Hi @brannmark ,

Thank you for reporting this. Based on your feedback and Lee's comments, I have set an empty object to `editorState`. Normally a specific content item would go into the `editorState`, but hopefully version [13.0.1](https://www.nuget.org/packages/Umbraco.UIBuilder/13.0.1) addresses your situation.

Regards,
Adrian
