### ISSUE TITLE
Built in actions doesnt work. Actions with settings models fails catastrophic

### ISSUE THREAD

**Issue by brannmark** [umbraco/Umbraco.UIBuilder.Issues#84]
**Describe the bug**
Adding built in actions import and export to a collection doesn't work.

When adding export action it fails with the following error:
![image](https://github.com/umbraco/Umbraco.UIBuilder.Issues/assets/1013748/1e6917a6-08d0-47df-8a02-198ac459306e)
![image](https://github.com/umbraco/Umbraco.UIBuilder.Issues/assets/1013748/820ea299-40a4-4027-8f7f-c2477c2dd31c)

When adding import action that has a settings model, IIS crashes without error logging.
![image](https://github.com/umbraco/Umbraco.UIBuilder.Issues/assets/1013748/f5668e6f-a718-45af-932d-b57b80c931f2)
![image](https://github.com/umbraco/Umbraco.UIBuilder.Issues/assets/1013748/a38a5bc5-ca7f-4b9b-b52e-68c9d36eb8b3)
![image](https://github.com/umbraco/Umbraco.UIBuilder.Issues/assets/1013748/ef798251-ec0e-4957-a5c3-f4671b11fea8)

**Steps To Reproduce**
1. Add built in import and export actions to a collection.
2. Go to collection
3. Select items to be exported
4. Action fails
5. See error in log viewer of Umbraco
6. Go to collection
7. Click on import action
8. Select file to be imported
9. Click on continue
10. Watch IIS crash

**Expected behavior**
Expected export file to be generated. Expected import to work.

**Environment (please complete the following information):**
 - Server OS: Windows
 - Browser: Chrome
 - Umbraco Version 13.0.3
 - Product Version 13.0.0

**Additional context**
Using custom repositories but they work for all other type of actions, search, list, edit, save and so on.

---
_This item has been added to our backlog AB#36293_

**Comment by acoumb** [comment]
Hi @brannmark ,

Thank you for bringing this to our attention. I have released a new version of `Umbraco.UIBuilder`, [13.0.1](https://www.nuget.org/packages/Umbraco.UIBuilder/13.0.1) with a fix to the export and import built-in actions.

If you are using the `Export` action as `ActionType.ContainerMenu`, I would advise using it as `ActionType.Bulk`, as the `Actions` menu will suffer changes in the coming versions.

Thank you,
Adrian
