### ISSUE TITLE
Dependency issue when installing UIBuilder alongside uSync in a v13 Umbraco website

### ISSUE THREAD

**Issue by matt-tolliday-iss** [umbraco/Umbraco.UIBuilder.Issues#85]
I have an Umbraco 13.0.3 site. I'm trying to install Umbraco.UIBuilder (13.0.1) but now it won't complete. This appears to be a dependency issue because uSync (13.0.1) and Umbraco.UIBuilder.Web.StaticAssets (13.0.1) have dependency on different versions of Microsoft.AspNetCore.Components.Web.

Steps To Reproduce
Steps to reproduce the behaviour:

Run a v13.0.3 Umbraco site
Install uSync (13.0.1)
Install Umbraco.UIBuilder (13.0.1)
See the following error...

<img width="567" alt="image" src="https://github.com/umbraco/Umbraco.UIBuilder.Issues/assets/80101704/e62bed21-2840-439d-bcbe-4bcd8ba399e5">

---
_This item has been added to our backlog AB#37144_

**Comment by matt-tolliday-iss** [comment]
@mattbrailsford Hi Matt, do you know whom might be able to assist with this?

**Comment by acoumb** [comment]
Hi @matt-tolliday-iss ,

Thank you for bringing this to our attention. The issue has been fixed with the latest patch release [13.0.2](https://www.nuget.org/packages/Umbraco.UIBuilder/13.0.2).

Regards,
Adrian
