### ISSUE TITLE
When creating an entity from a context app, the FK property value is set to 0, not to the related context ID

### ISSUE THREAD

**Issue by matt-tolliday-iss** [umbraco/Umbraco.UIBuilder.Issues#86]
**Describe the bug**
When creating an entity from a context app, the FK property value is set to 0, not to the related context ID.

In the below example, a context app configured for the Member has a custom table called Enquiry, where the configuration uses the ID field of the Enquiry as ID property, and the MemberID field as FK identifier. When using the context app to create a new Enquiry, the value of the MemberID FK is not set to the current member being viewed, but it is set to 0. This means that the new record is available for any Member.

**Steps To Reproduce**
1. Create context app for members
2. create new entity in context app UI
3. check data value set for FK property ID

```
cfg
    .WithSection("member")
    .WithTree("member", cfg => cfg
        .AddContextApp("Enquiries", contextAppConfig => {
            contextAppConfig.AddCollection<EnquiryDto>(x => x.Id, id => id.MemberId, "Member Enquiry", "Member Enquiries", "An enquiry", "icon-help-alt", "icon-help-alt", ccfg => ccfg
            .AddFilterableProperty(p => p.Text, filterconfig => filterconfig
                .SetLabel("Text")
                .SetDescription("The content of the enquiry")
            )
            .SetNameProperty(p => p.Title)
            .SetDateCreatedProperty(p => p.CreatedOn)
            .SetDeletedProperty(p => p.IsDeleted)
            .ListView(listViewConfig => listViewConfig
                .AddField(p => p.Text)));
```

**Expected behavior**
The value stored in the property marked as the FK identifier should be the ID of the context app node - in the above example, i would have expected MemberId on the Enquiries table to be populated with the Member ID.

As the value is saved as 0 (default non-nullable int) then it becomes available against every entity (member in this case)

**Screenshots**
<img width="331" alt="image" src="https://github.com/umbraco/Umbraco.UIBuilder.Issues/assets/80101704/a7cec62c-795f-46ac-adf0-3435440b0ddf">

**Environment
 - Umbraco Version 13.0.1
 - Product Version 13.0.1

---
_This item has been added to our backlog AB#37143_

**Comment by acoumb** [comment]
Hi @matt-tolliday-iss ,

You can find a fix for this with today's release candidate version of [13.1.0](https://www.nuget.org/packages/Umbraco.UIBuilder/13.1.0-rc1).

Thank you,
Adrian
