### ISSUE TITLE
Dependency issue when installing UIBuilder alongside Umbraco Commerce in a v13 Umbraco website

### ISSUE THREAD

**Issue by patlit** [umbraco/Umbraco.UIBuilder.Issues#87]
Trying to install Umbraco UI Builder version 13.0.1 on a site (version 13.0.3) where Umbraco Commerce version 13.0.0 is installed.
Results in an dependency issue with Microsoft.AspNetCore.Components.Web
![image](https://github.com/umbraco/Umbraco.UIBuilder.Issues/assets/54680084/c8fa1bff-00bd-4715-afda-1d0919dce1b2)

---
_This item has been added to our backlog AB#37142_

**Comment by acoumb** [comment]
Hi @patlit ,

Thank you for bringing this to our attention. The issue has been fixed with the latest patch release [13.0.2](https://www.nuget.org/packages/Umbraco.UIBuilder/13.0.2).

Regards,
Adrian
