### ISSUE TITLE
Dependency conflict running v10 on Umbraco 11

### ISSUE THREAD

**Issue by philipdanielhayton** [umbraco/Umbraco.UIBuilder.Issues#89]
We have a site that is running v11 of Umbraco and want to use UI Builder. Unfortunately there's a dependency conflict when using UIBuilder v10 in relation to the 'Microsoft.AspNetCore.Components.Web'.

UI Builder requires Microsoft.AspNetCore.Components.Web to be < 7.0.0, but one of our other dependencies requires >= 7.0.0. 

Since Umbraco 11 is on .NET 7.0 it seems reasonable to have Microsoft.AspNetCore.Components.Web 7.0.0 as a baseline.

Is there anyway to add support for this scenario?

---
_This item has been added to our backlog AB#37140_

**Comment by acoumb** [comment]
Hi @philipdanielhayton ,

The version for `Microsoft.AspNetCore.Components.Web` has been updated with today's patch releases.

Given Umbraco 11 is EOL, I would strongly recommend you upgrading to version 13. 

Regards,
Adrian
