### ISSUE TITLE
Upgrade from 13.0.3 to 13.1.0-rc1 breaks existing custom repository

### ISSUE THREAD

**Issue by Padbury** [umbraco/Umbraco.UIBuilder.Issues#91]
**Describe the bug**
I have a very simple, only partially implemented custom repository that works fine in 13.0.3 but as soon as I update to 13.1.0-rc1 all attempts to view an entity result in the following error: UdiConverter cannot convert from System.String.

**Steps To Reproduce**
1. Create a simple custom repository
2. Add a small list view to a collection
3.  Wire up the ui builder: such as:
  ```
builder.AddUIBuilder(cfg =>
   {
       cfg.AddSectionAfter("media", "Store", sectionConfig => sectionConfig
               .Tree(treeConfig => treeConfig
                   .AddCollection<EditableProduct>(x => x.Id, "Products", "Products", "A product entity", "icon-frame-alt", "icon-frame-alt", collectionConfig => collectionConfig
                       .SetNameProperty(p => p.Name)
                       .ListView(listViewConfig => listViewConfig
                           .AddField(p => p.Code).SetHeading("Code")
                       )
                       .SetRepositoryType<ProductBackofficeRepository>()
                       .Editor(editorConfig => editorConfig
                           .AddTab("General", tabConfig => tabConfig
                               .AddFieldset("Details", x => x
                               .AddField(p => p.Code).SetDataType("Textstring").MakeRequired().SetDescription("The product code")  
                               )    
                           )
                       )
                   )
               )
           );

   });
```

**Expected behavior**
Entity is shown without an error

**Screenshots**
![Capture](https://github.com/umbraco/Umbraco.UIBuilder.Issues/assets/2233234/d3ea35ab-ceeb-4b82-ba75-524678831564)

**Environment (please complete the following information):**
 - Umbraco Version 13.0.3 and 13.1.0
 - Product Version 13.1.0-rc1

**Additional context**
I created a super simple custom repo that only (currently) implements the GetImpl and the GetPagedImpl functions. In the previous version of the UIBuilder (13.0.3) this worked fine, however it didn't properly support the Richtext Editor. However, reading around, the RTE issue is fixed with this rc. Upgrading the version required an additional function to be implemented on the custom repo (SaveRelationImpl) which I added, but as unimplemented. However, on updating, I get the attached error when attempting to view on of the returned entities. In attempting to debug this, I ended up with a super simple class of this:

` public class EditableProduct
 {
      public int Id { get; set; }
      public string Code { get; set; } = null!;
      public string Name{ get; set; } = null!;
}`

Reverting back to 13.0.3 fixes this issue but then if I try to add an RTE to my model, the RTE doesn't render. So caught between two issues.

Thanks

**Comment by acoumb** [comment]
Hi @Padbury ,

Could you share your custom repository as well? I have tried your use case using the default UI Builder repository, and I haven't encountered the issue you've reported (you can check my test [here](https://us02web.zoom.us/clips/share/AmU9ktidhu8W_KAxK8r05a33pp9obUjWeuWo2t-BUhmIT_OC7LFA_o904emRQhOAydIVAA9ER_at3FdR62dCJFxO.DJLcTVYRA8MHOV0X)).
![image](https://github.com/umbraco/Umbraco.UIBuilder.Issues/assets/95346674/90471515-3061-45f4-bdd2-cffd38fd5f2c)
![image](https://github.com/umbraco/Umbraco.UIBuilder.Issues/assets/95346674/17d2fe0d-3d07-466d-bce6-70fad53a85c1)

Regarding the RTE issue, this was addressed by the CMS team with version `13.1` of Umbraco. Could you update your website and try again?

Thank you,
Adrian

**Comment by Padbury** [comment]
Hiya, 

Thanks for reviewing. Here's my repo though it's only implementing a couple of the functions (and even then it's not finished) but it will give you an idea of what I've got. The flow doesn't get as far as the repo though. I popped in some breakpoints and the constructor isn't getting hit. However, if you were unable to replicate then it's possible it's something else externally, such as a package, that might be causing the issue. I'll investigate further today. Here's my repo anyway.

Thanks again

```
public class ProductBackofficeRepository(RepositoryContext context, IProductService productService, IMapper mapper) : Repository<EditableProduct, int>(context)
  {
      protected override void DeleteImpl(int id)
      {
          throw new NotImplementedException();
      }

      protected override IEnumerable<EditableProduct> GetAllImpl(Expression<Func<EditableProduct, bool>>? whereClause = null, Expression<Func<EditableProduct, object>>? orderBy = null, SortDirection orderByDirection = SortDirection.Ascending)
      {
          throw new NotImplementedException();
      }

      protected override long GetCountImpl(Expression<Func<EditableProduct, bool>> whereClause)
      {
          throw new NotImplementedException();
      }

      protected override int GetIdImpl(EditableProduct entity)
      {
          throw new NotImplementedException();
      }

      protected override EditableProduct GetImpl(int id)
      {
          return mapper.Map<EditableProduct>(productService.Get(id));
      }

      protected override PagedResult<EditableProduct> GetPagedImpl(int pageNumber, int pageSize, Expression<Func<EditableProduct, bool>>? whereClause = null, Expression<Func<EditableProduct, object>>? orderBy = null, SortDirection orderByDirection = SortDirection.Ascending)
      {
          var products = productService.Fetch(pageNumber, pageSize, ProductSortOrder.Name, false, "");
          var i = new PagedResult<EditableProduct>(products?.TotalResults ?? 0, pageNumber, pageSize)
          {
              Items = mapper.Map<List<EditableProduct>>(products)
          };
          return i;
      }

      protected override IEnumerable<TJunctionEntity> GetRelationsByParentIdImpl<TJunctionEntity>(int parentId, string relationAlias)
      {
          throw new NotImplementedException();
      }

      protected override EditableProduct SaveImpl(EditableProduct entity)
      {
          throw new NotImplementedException();
      }

      protected override TJunctionEntity SaveRelationImpl<TJunctionEntity>(TJunctionEntity entity)
      {
          throw new NotImplementedException();
      }
  }
```

**Comment by acoumb** [comment]
I managed eventually to simulate something and got the error thrown, I will investigate it and prepare a fix for it.

Thanks for the help

**Comment by acoumb** [comment]
@Padbury version [13.1.0-rc2](https://www.nuget.org/packages/Umbraco.UIBuilder/13.1.0-rc2) is out with a fix to your reported issue.

Thank you for your help with this,
Adrian
