### ISSUE TITLE
Outdated dependency on CsvHelper

### ISSUE THREAD

**Issue by arknu** [umbraco/Umbraco.UIBuilder.Issues#95]
**Describe the bug**
UI Builder seems to have an outdated dependency on CsvHelper version 27.2.1

**Steps To Reproduce**
Have an indirect dependency on CsvHelper (31.0.2 is the current version).
Try installing UI Builder. It will fail.

**Expected behavior**
Given that UI Builder 13.1 was just released, I do not expect it to have a version-locked dependency on a CsvHelper version (27.x) released in 2021. Rather, it should have a dependency on a recent version and not be locked to strictly to a specific version.

**Comment by acoumb** [comment]
Hi @arknu ,

With latest update of UIBuilder - [13.1.1](https://www.nuget.org/packages/Umbraco.UIBuilder/13.1.1), I've left `CsvHelper` to `27.2.1`, with an update to the latest version coming with v14.

Regards,
Adrian
