### ISSUE TITLE
Childcollection with int as ID breaks after upgrade to 13.1.2

### ISSUE THREAD

**Issue by patlit** [umbraco/Umbraco.UIBuilder.Issues#99]
After upgrading to UI Builder 13.1.2 my childcollection (using custom repositories) crashes with error "startIndex ('-28') must be a non-negative value. (Parameter 'startIndex') Actual value was -28."

Definition:
![image](https://github.com/umbraco/Umbraco.UIBuilder.Issues/assets/54680084/680074f4-c72c-4d24-8fdd-cfa76bddd5e5)

api call "FindEntites" gives server error 500:
![image](https://github.com/umbraco/Umbraco.UIBuilder.Issues/assets/54680084/5f6a1581-d0cf-477c-8917-37b1d8d811a9)
Payload:
![image](https://github.com/umbraco/Umbraco.UIBuilder.Issues/assets/54680084/2b1c48cc-7e84-45ad-a42f-b1fd0dde8a6e)

Response:
{
    "ExceptionMessage": "startIndex ('-28') must be a non-negative value. (Parameter 'startIndex')\r\nActual value was -28.",
    "ExceptionType": "System.ArgumentOutOfRangeException, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e",
    "StackTrace": "   at System.ArgumentOutOfRangeException.ThrowNegative[T](T value, String paramName)\r\n   at System.String.ThrowSubstringArgumentOutOfRange(Int32 startIndex, Int32 length)\r\n   at Umbraco.UIBuilder.Services.EntityService.FindEntities(CollectionConfig collection, Object parentId, Int32 pageNumber, Int32 pageSize, String query, IDictionary`2 filters, String dataViewAlias, String orderBy, String orderDirection)\r\n   at Umbraco.UIBuilder.Web.Controllers.Api.UIBuilderApiController.FindEntities(FindEntitiesPostModel postModel)\r\n   at lambda_method11927(Closure, Object, Object[])\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()\r\n--- End of stack trace from previous location ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)"
}

Any help would be appreciated, we plan to go live with the site in 2 weeks and this needs to work.

Best regards
Patrik

**Comment by patlit** [comment]
Hi, any thoughts on this? Do we need to downgrade UI Builder?
Best regards
Patrik

**Comment by acoumb** [comment]
Hi @patlit ,

I will release a patch version with a fix for this today.

Regards,
Adrian

**Comment by patlit** [comment]
Thank you Adrian! That will be perfect, was getting a bit nervous for our release on next tuesday :)

**Comment by acoumb** [comment]
@patlit version [13.1.3](https://www.nuget.org/packages/Umbraco.UIBuilder/13.1.3) is now on NuGet.

**Comment by patlit** [comment]
@acoumb Thanks Adrian!  Just tested and i think everything works as expected now. 
Best regards
Patrik
